name: Node.js CI

on:
  pull_request:
    branches:
      - blog
    paths:
      - '**' # Trigger for any changes in the PR
    types:
      - opened
      - synchronize

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  merge-approval:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Check if tests passed
      run: exit $(echo "${{ needs.build-and-test.outcome }}" | grep -c "success")
