name: new-push

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Update server
    runs-on: ubuntu-latest
    steps:
    - name: update server with new code
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: ./deploy.sh
